language:
  ruby
rvm:
  - 2.2
  - jruby
cache:
  - bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: be692c06b6c26db8c7fa1c52bd5f46b6ef00bff9
  app: supp2u
  on:
    repo: Lambda-Labs-Weedmaps-1/Supp2U
script:
  -rspec